### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Comicus** [nyyr/EnchantCheck#1]
I am having a conflict between Enchant Check and Azerite Button.  AB overwrites EC.  I was wondering if the EC button could be to the left of AB or make it moveable like Pawn.  Pawn lets you pick where you want the button to be placed.

**Comment by b-morgan** [comment]
Change line 123 in frames.xml and move the button wherever you'd like (probably only need to change x). There isn't a lot of free space in the character frame. Enchant Check currently doesn't have any options so adding the first one is a lot of work.
